### ISSUE TITLE
Unable to install using CocoaPods

### ISSUE THREAD

**Issue by FergyKay** [readium/r2-opds-swift#44]
I'm trying install using CocoaPods following the directives in the ReadMe but i'm getting this error `[!] Invalid Podfile file: syntax error, unexpected '\n', expecting =>.`. Please assist

**Comment by mmenu-mantano** [comment]
Hello,

Could you please share your complete Podfile?

**Comment by FergyKay** [comment]
`# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Readium' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Readium
pod 'ReadiumOPDS', :git => 'https://github.com/readium/r2-opds-swift.git', '~> 1.0.4'

end`

**Comment by mmenu-mantano** [comment]
Can you try removing the version specifier for ReadiumOPDS? Or if you really want a specific version, you can use `:tag` instead (ie. CocoaPods documentation).

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Readium' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Readium
pod 'ReadiumOPDS', :git => 'https://github.com/readium/r2-opds-swift.git'

end
```

**Comment by FergyKay** [comment]
Without the version specifier, `[!] Unable to find a specification for R2Shared depended upon by ReadiumOPDS`

With the :tag, `[!] Unable to find a specification for R2Shared depended upon by ReadiumOPDS`

**Comment by aferditamuriqi** [comment]
I am closing this issue, as the pod specs have been updated, if there is still an issue, please open a new issue.
