### ISSUE TITLE
rename repo to r2-opds-swift

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-opds-swift#7]
creating this issue as a reminder for myself

**Comment by HadrienGardeur** [comment]
We can re-open that discussion but basically:

- the OPDS parser is useful, even outside of the context of R2 itself (for example, an app based on FolioReader could still benefit from using this parser)
- in terms of dependency, it's only tied to r2-shared-swift

That's the main reason why this repo isn't prefixed with r2-*.

**Comment by aferditamuriqi** [comment]
I thought about that as well and fully agree. but we can discuss this and why i thought of renaming.
